service: process-inbox
plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs6.10
  environment:
    REDIS_HOST: 127.0.0.1:6379
    DB_HOST: mongodb://
functions:
  getInbox:
    handler: app/router.getInbox
    events:
      - http:
          cors: true
          method: get
          path: inbox/get
  sendTo:
    handler: app/router.sendTo
    events:
      - http:
          method: post
          cors: true
          path: inbox/send
  fetchProcess:
    handler: app/router.fetchProcess
    events:
      - http:
          method: post
          cors: true
          path: inbox/fetch
